### ISSUE TITLE
Operation::setTo omits target property if the source property doesn't exist

### ISSUE THREAD

**Issue by eremem** [mark-gerarts/automapper-plus#53] opened 2020-02-27 14:44 UTC
My target class has a property which the source class is lacking. To this target property I would like to be able to assign a particular value during the mapping. According to the documentation Operation::setTo seems to do the job, but at the moment it ignores target properties for which there are no equivalent source properties. Is there any reason behind this behaviour? I looked at the Options object too, but see no relevant setting. I know I could define a callback, but Operation::setTo is way more elegant in this case.

**Comment by mark-gerarts** [comment] 2020-02-27 16:29
Yes you are right, this is not the intended behaviour. A fix for this has been pushed, it's available in release 1.3.9. Thanks for reporting!

**Closed as completed by mark-gerarts** 2020-02-27 16:29 UTC
