### ISSUE TITLE
Last version 1.3.11 is probably not minor upgrade :) 

### ISSUE THREAD

**Issue by VitaliiIsaenko** [mark-gerarts/automapper-plus#59] opened 2020-05-04 12:12 UTC
I experience a problem after composer updated the minor version of the amazing library you develop.
As far as I understood it's because we don't use typed variables yet. We are still sticking to the annotations. 
A very nice change but I'd suggest you consider implementing backwards capability or upgrade a major version of the library.
I can't achieve proper formatting of the stack trace so I will provide it using screenshots, hope it helps 
![image](https://user-images.githubusercontent.com/16831919/80964109-9645d000-8e10-11ea-932f-6910627d074c.png)
![image](https://user-images.githubusercontent.com/16831919/80964392-10765480-8e11-11ea-841d-130de9bd9a1a.png)
![image](https://user-images.githubusercontent.com/16831919/80964402-14a27200-8e11-11ea-9d1e-062834542f0b.png)
![image](https://user-images.githubusercontent.com/16831919/80964408-1835f900-8e11-11ea-8897-ef28f49a956f.png)
![image](https://user-images.githubusercontent.com/16831919/80964413-1bc98000-8e11-11ea-9594-7b374521cd84.png)
![image](https://user-images.githubusercontent.com/16831919/80964421-1ff59d80-8e11-11ea-9945-03d39deeb51e.png)
![image](https://user-images.githubusercontent.com/16831919/80964429-22f08e00-8e11-11ea-87fb-8f40f4df0a47.png)
![image](https://user-images.githubusercontent.com/16831919/80964437-284dd880-8e11-11ea-97e4-4e45de053ed3.png)
![image](https://user-images.githubusercontent.com/16831919/80964444-2c79f600-8e11-11ea-9a65-8d187553dffb.png)
![image](https://user-images.githubusercontent.com/16831919/80964457-33a10400-8e11-11ea-99b8-b4c8c9ec2fe4.png)

**Comment by mark-gerarts** [comment] 2020-05-04 12:33
Thanks for taking the time for the screenshots! I didn't expect this to be a BC breaking release, since all test from 7.1 to 7.4 were green. I'm guessing your code contains an edge case for which we don't have a test yet.

I'll investigate the problem and hopefully release a fix soon. In the meantime you'll have to stick to 1.3.10.

**Comment by VitaliiIsaenko** [comment] 2020-05-04 12:35
Sure, already rolled back. Let me know if any additional info would help you to identify this edge case and I can try to provide it.

**Comment by mark-gerarts** [comment] 2020-05-05 12:23
Hi @VitaliiIsaenko, the fix was quite easy, but the hard part was trying to reproduce it. Is it possible that you use a custom constructor in your mapping that can sometimes return `null`?

I've pushed a fix for this scenario on `hotfix/reflection-class-null`. If you can confirm this fixes it for your use case, I'll merge it in master and tag a new release.

**Comment by VitaliiIsaenko** [comment] 2020-05-05 14:50
Yes, looks like it solves the problem, I don't have the issue with the fix :+1: 

I don't have any custom constructor in the company model but I use this trick quite often (though don't know if it is related)
```
$config->registerMapping(DataType::ARRAY, Company::class)
    ->beConstructedUsing(function (array $a) {
        return isset($a['id']) ? null : new Company();
    })
```

**Comment by mark-gerarts** [comment] 2020-05-05 15:04
I think that's exactly what's causing this :)

Anyway, thanks for letting me know that it works. The new version (1.3.12) is pushed!

**Closed as completed by mark-gerarts** 2020-05-05 15:04 UTC
Labels: bug
