### ISSUE TITLE
Doctrine proxies are not supported

### ISSUE THREAD

**Issue by BoShurik** [mark-gerarts/automapper-plus#26] opened 2018-10-09 11:50 UTC
The problem is here: https://github.com/mark-gerarts/automapper-plus/blob/master/src/PropertyAccessor/PropertyAccessor.php#L95-L102

```php
    protected function setPrivate($object, string $propertyName, $value): void
    {
        $setter = function($value) use ($propertyName) {
            $this->{$propertyName} = $value;
        };
        $boundSetter = \Closure::bind($setter, $object, get_class($object));
        $boundSetter($value);
    }
```

`get_class($object)` returns proxy class name. This scope does not have access to private properties. Sadly this code does not throw any exception.

**Comment by mark-gerarts** [comment] 2018-10-09 15:51
Hi. I've created a repository that reproduces this issue: https://github.com/mark-gerarts/automapper-plus-issue-26.

So, when we try to map a `Product`, we get a `Category` with only its ID set (screenshot). This is because of the way Doctriny lazily loads entities using properties. This is the issue you're having, right?

![image](https://user-images.githubusercontent.com/11940560/46681245-197a5200-cbeb-11e8-8c88-38b68d002050.png)

As a quick fix his can be solved in the application by adding a `fetch=eager` to Doctrine's relation definition. However, it would be interesting to make it work without having to do this. Currently, my only idea is to add an option to the config to mark certain properties as being a Doctrine entity. We could then make Doctrine load these entities once we're mapping them. We could even add an option to autodetect Doctrine entities (I think it should be possible).

Any thoughts/better ideas?

**Comment by BoShurik** [comment] 2018-10-09 21:15
> This is the issue you're having, right?

Almost. In my case pass proxies to `mapToObject` method
```php
$model = new ProductDto();
$object = $this->entityManager->getReference(Product::class, 1);
$this->autoMapper->mapToObject($model, $object);
```
(In rare cases it is possible to get proxy object when using DoctrineParamConverter)

As a workaround I've used a custom PropertyAccessor:
```php
use AutoMapperPlus\PropertyAccessor\PropertyAccessor as BasePropertyAccessor;
use Doctrine\Common\Persistence\Proxy;
use Symfony\Component\PropertyAccess\PropertyAccess;
use Symfony\Component\PropertyAccess\PropertyAccessor;

class SymfonyPropertyAccessor extends BasePropertyAccessor
{
    /**
     * @var PropertyAccessor
     */
    private $propertyAccessor;

    public function __construct(PropertyAccessor $propertyAccessor = null)
    {
        $this->propertyAccessor = $propertyAccessor ?? PropertyAccess::createPropertyAccessor();
    }

    /**
     * @inheritDoc
     */
    protected function setPrivate($object, string $propertyName, $value): void
    {
        if ($object instanceof Proxy) {
            $this->propertyAccessor->setValue($object, $propertyName, $value);
        } else {
            parent::setPrivate($object, $propertyName, $value);
        }
    }
}
```

**Comment by mark-gerarts** [comment] 2018-10-11 19:52
Alright. I've been able to reproduce this. I'll experiment with decorating the Symfony PropertyAccessor for cases like this, similarly to what you did here (and discussed in #16). It might be added in a future version then.

That being said, wouldn't the following solve your issue as well, without the need for a custom accessor (assuming detached state is the problem):

```
$productDto = new ProductDto();
$product = $this->mapper->map($productDto, Product::class);
$this->entityManager->merge($product);
```

**Comment by BoShurik** [comment] 2018-10-11 20:07
In my case `ProductDto` does not contain an `id` property. 
Fortunately architecture allow to easily change `PropertyAccessor`'s implementation

**Comment by mark-gerarts** [comment] 2018-10-11 20:25
Ah yeah, a merge wouldn’t work then. Good thing you’ve got a workaround! I’ll keep this issue open until I’ve had the chance to experiment with the property accessor component. Thanks for the discussion!

**Comment by vasilake-v** [comment] 2018-11-19 08:53
I think unproxy-ing doctrine entities is not a "mapper" responsibility, because it may lead to unwanted/unpredictable behavior. You could get mapped properties where you don't need them and make extra SQL queries without any reason.
Of course, all depends on your project, your needs and how resource heavy is your doctrine entity. 
I would suggest, having the entity member with `fetch=lazy` and where you need it unproxy-ed just write a separate method in the repository layer and reference this property, this will build the required `JOIN`s and which fill-up the members you need. This will be executed in a single query instead of multiple SQL queries( when uproxing on demand in mapper for each property).

**Comment by mark-gerarts** [comment] 2018-11-19 10:08
Hi @slava-v, definitely agree with all your points. You don't want a third-party library to start loading your entities and performing queries. I was thinking to maybe provide a Doctrine-specific accessor you could enable via options. It's not a high priority at the moment though.

Your proposed solution is a good one in the meantime. To summarize, you could either:
- Ensure your referenced entities are loaded by calling the relevant method before performing the mapping
- Set the fetch mode to eager in the doctrine config
- Set the fetch mode to eager only for the relevant query

**Comment by BoShurik** [comment] 2018-11-19 10:26
> Set the fetch mode to eager in the doctrine config
Set the fetch mode to eager only for the relevant query

This will not work for ODM (my case)

**Comment by BoShurik** [comment] 2018-11-19 10:33
Anyway, in case of Liskov Substitution Principle this example should work, but it did not:
```php
class Foo
{
    private $name;

    public function __construct(string $name)
    {
        $this->name = $name;
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }
}

class FooChild extends Foo
{

}

class FooDTO
{
    public $name;
}

$config = new AutoMapperConfig();
$config->registerMapping(FooDTO::class, Foo::class);

$mapper = new AutoMapper($config);

$foo = new Foo('foo');
$fooChild = new FooChild('foo-child');

$fooDTO = new FooDTO();
$fooDTO->name = 'foo-dto';

$mapper->mapToObject($fooDTO, $foo);

dump($foo);

$mapper->mapToObject($fooDTO, $fooChild);

dump($fooChild);
```

**Comment by mark-gerarts** [comment] 2018-11-19 12:06
Hi @BoShurik, which version of the library are you using? I did a quick test with your sample code, and it seems to work fine on master. Adherence to the substitution principle was added in 1.2.2, so maybe you're using an older version.

**Comment by BoShurik** [comment] 2018-11-19 12:10
`1.2.3`

```
Foo {#11
  -name: "foo-dto"
}
FooChild {#12
  -name: "foo-child"
  +"name": "foo-dto"
}
```

**Comment by BoShurik** [comment] 2018-11-19 12:13
I tried `master` but result is the same

**Comment by mark-gerarts** [comment] 2018-11-19 17:36
My test was too quick it seems :) I've implemented a fix for this on master. I'll be drafting a new release in the following days!

I'll close this issue, but if you still encounter problems, feel free to reopen or create a new one.

**Closed as completed by mark-gerarts** 2018-11-19 17:36 UTC
Labels: enhancement
