### ISSUE TITLE
Not mapping extending classes

### ISSUE THREAD

**Issue by yhnehc** [mark-gerarts/automapper-plus#10] opened 2017-12-01 22:34 UTC
if classA entends classBase. All attributes lived in classBase. After mapping, will get an empty class A object.

In my case, I have classA extends classBase.
 I want map classA to ClassADto. my class have a list of classA. 
after mapping, I get a list of empty classADto.

**Comment by mark-gerarts** [comment] 2017-12-02 12:56
That is definitely unwanted behaviour. I'll try to look into it this weekend.

**Comment by mark-gerarts** [comment] 2017-12-02 15:33
This should be fixed in the new release (v1.0.6). If you still have problems, feel free to reopen this issue.

**Comment by yhnehc** [comment] 2017-12-05 17:42
Thanks for doing this. I'm still getting some problems. I use a get method in base class, but I'm getting that method not found in extending class.

class A extends class B{
}

class B{
public $x;

public function setX(){}
}

I'm Mapping class A and get Attempted to call an undefined method named \"setX\" of class \"class A".

**Comment by mark-gerarts** [comment] 2017-12-05 18:10
Weird, methods should remain unchanged. I'm not entirely sure if I understand the situation correctly though. Could you explain which class you're mapping exactly? Class A to a DTO, or a DTO to class A?

If you can provide a code sample of how you defined the mapping, that would help as well!

**Comment by yhnehc** [comment] 2017-12-05 18:11
Im mapping class A to DTO

**Comment by mark-gerarts** [comment] 2017-12-05 18:44
I've tested using the following setup: [gist](https://gist.github.com/mark-gerarts/030b4ad315ad72c72fd23fb834f66600). This seems to work fine.

**Comment by yhnehc** [comment] 2017-12-07 23:33
I see the difference. I use a private property instead of public property.

**Comment by mark-gerarts** [comment] 2017-12-14 21:23
I tested with the sample code in the gist again. Making either property private still doesn't give me any errors, and the mapping keeps working correctly. 

Can you provide a small piece of sample code for which you're getting the error? I've tried a bunch of setups, but can't reproduce this :(

**Closed as completed** 2018-08-26 13:23 UTC
Labels: bug
